//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandBClient.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedCustomer
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public string IsVisited { get; set; }
        public string Status { get; set; }
        public string LeadSource { get; set; }
        public string PhoneNumber { get; set; }
        public string DeletedBy { get; set; }
        public string OtherReason { get; set; }
    }
}
