////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated from a template.
////
////     Manual changes to this file may cause unexpected behavior in your application.
////     Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace LandBClient.Core
//{
//    using System;
//    using System.Data.Entity;
//    using System.Data.Entity.Infrastructure;
    
//    public partial class LandBDB_TestEntities : DbContext
//    {
//        public LandBDB_TestEntities()
//            : base("name=LandBDB_TestEntities")
//        {
//        }
    
//        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
//        //{
//        //    throw new UnintentionalCodeFirstException();
//        //}
    
//        public virtual DbSet<Customer> Customers { get; set; }
//        public virtual DbSet<DeletedCustomer> DeletedCustomers { get; set; }
//        public virtual DbSet<TUser> TUsers { get; set; }
//    }
//}
